site_name: TP Big Data
site_description: Les Travaux Pratiques du cours Big Data
site_author: Lilia Sfaxi
site_url: http://INSATunisia.github.io/TP-BigData/

# Repository
repo_name: INSATunisia/TP-BigData
repo_url: https://github.com/INSATunisia/TP-BigData

# Copyright
copyright: 'Copyright &copy; 2017 - 2024 Lilia Sfaxi'

# Theme directory
plugins:
  - search
  - autolink_references:
        autolinks:
            - reference_prefix: AF-
              target_url: https://linear.com/AF-<num>
            - reference_prefix: PROJ-
              target_url: https://jiracloud.com/PROJ-<num> 
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - footnotes
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  favicon: img/favicon.ico
  logo: "img/logo.png"
  palette:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
    primary: Blue
    accent: Yellow
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'
social:
  - type: globe
    link: http://liliasfaxi.wix.com/liliasfaxi
  - type: github-alt
    link: https://github.com/liliasfaxi
  - type: twitter
    link: https://twitter.com/lillitou
  - type: linkedin
    link: https://www.linkedin.com/in/liliasfaxi/


# Page tree
pages:
   - Travaux Pratiques Big Data: 'index.md'
   - TP1 - Le traitement Batch avec Hadoop HDFS et Map Reduce: 'tp1.md'
   - TP2 - Traitement par Lot et Streaming avec Spark: 'tp2.md'
   # TP3 - La Collecte de Données avec le Bus Kafka: 'tp3.md'
   # TP4 - Stockage de Données dans une Base NOSQL avec HBase: 'tp4.md'


